In [1]:
import numpy as np


In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [3]:
#create a 2D array  
a2 = np.array([[1, 2, 3,4,5], [6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
#creating a 3d array
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
print(a2.shape)
print(a2.ndim)
print(a2.dtype)

(2, 5)
2
int64


In [13]:
np.arange(10)
np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
np.random.randint(1,11, size=(2,3))

array([[ 1,  6,  3],
       [ 3,  2, 10]], dtype=int32)

In [15]:
x = np.array([[7,2,3],
              [4,5,6],
              [1,8,9]])
y = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(x)
print(y)

[[7 2 3]
 [4 5 6]
 [1 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
