In [1]:
import numpy as np


In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [3]:
#create a 2D array  
a2 = np.array([[1, 2, 3,4,5], [6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
#creating a 3d array
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
print(a2.shape)
print(a2.ndim)
print(a2.dtype)

(2, 5)
2
int64


In [6]:
np.arange(10)
np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
np.random.randint(1,11, size=(2,3))

array([[ 3,  7,  3],
       [ 5, 10,  6]], dtype=int32)

In [8]:
x = np.array([[7,2,3],
              [4,5,6],
              [1,8,9]])
y = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(x)
print(y)

[[7 2 3]
 [4 5 6]
 [1 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(x*y)



[[ 7  4  9]
 [16 25 36]
 [ 7 64 81]]


In [10]:
print(x@y) #matrix multiplication


[[ 36  48  60]
 [ 66  81  96]
 [ 96 114 132]]


In [11]:
np.dot(x,y) #matrix multiplication using dot product

array([[ 36,  48,  60],
       [ 66,  81,  96],
       [ 96, 114, 132]])

In [12]:
x.prod() #product of all elements in the array

np.int64(362880)

In [13]:
x.mean() #mean of all elements in the array

np.float64(5.0)

In [14]:
y.mean()

np.float64(5.0)

In [15]:
print(x) 

[[7 2 3]
 [4 5 6]
 [1 8 9]]


In [16]:
x.mean(axis=0) #mean of each column

array([4., 5., 6.])

In [17]:
y.mean(axis=0)

array([4., 5., 6.])

In [18]:
print(x.sum()) #sum of all elements in the array
print(x.std()) #standard deviation
print(x.var()) #variance

45
2.581988897471611
6.666666666666667


In [19]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
print(np.percentile(a,25)) #1st quartile
print(np.percentile(a,50)) #median
print(np.percentile(a,75)) #3rd quartile

[1 2 3 4 5 6 7 8 9]
3.0
5.0
7.0


In [20]:
b = np.random.randint(1,11,(5,5)) #size of matrix
print(b)

[[ 2  7  6  2  9]
 [ 7  5  9  4  9]
 [ 4  3 10  4  2]
 [ 4 10  4  7  5]
 [ 5  8  8  4  3]]


In [21]:
x = np.random.randint(11,100,(4,4))
print(x)

[[90 91 13 34]
 [54 18 44 90]
 [45 55 16 31]
 [55 63 67 65]]


In [22]:
print(x[0]) #1st row
print(x[0,1]) #1st row, 2nd column
print(x[-1]) #last row

print(x[:3]) 
print(x[3:])

[90 91 13 34]
91
[55 63 67 65]
[[90 91 13 34]
 [54 18 44 90]
 [45 55 16 31]]
[[55 63 67 65]]
